CREATE DATABASE Skeleton CHARACTER SET utf8 COLLATE UTF8_GENERAL_CI;
USE Skeleton; 

CREATE TABLE User(
	id 			INTEGER AUTO_INCREMENT PRIMARY KEY,
	firstName	VARCHAR(30) NOT NULL,
	lastName		VARCHAR(30) NOT NULL,
	email			VARCHAR(30) NOT NULL UNIQUE
);